---
# Source: gitwebhookproxy/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/target-platform: kubernetes
  labels:
    app: gitwebhookproxy
    group: com.stakater.platform
    provider: stakater
    version: v0.2.68
    chart: "gitwebhookproxy-v0.2.68"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: gitwebhookproxy
data:
    provider: github
    upstreamURL: https://jenkins.tools.stackator.com
    allowedPaths: /github-webhook,/project
    ignoredUsers: stakater-user
    allowedUsers: myuser

