---
# Source: gitwebhookproxy/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: gitwebhookproxy
    group: com.stakater.platform
    provider: stakater
    version: v0.2.65
    chart: "gitwebhookproxy-v0.2.65"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: gitwebhookproxy
data:
    secret: ""
