---
# Source: gitwebhookproxy/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  labels:
    app: gitwebhookproxy
    group: com.stakater.platform
    provider: stakater
    version: v0.2.78
    chart: "gitwebhookproxy-v0.2.78"
    release: "gitwebhookproxy"
    heritage: "Tiller"
  name: gitwebhookproxy
data:
    secret: ""

