apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/target-platform: kubernetes
  labels:
{{ include "gitwebhookproxy.labels.stakater" . | indent 4 }}
{{ include "gitwebhookproxy.labels.chart" . | indent 4 }}
{{- if .Values.gitWebhookProxy.useCustomName }}
  name: {{ .Values.gitWebhookProxy.customName }}
{{- else }}
  name: {{ template "gitwebhookproxy.name" . }}
{{- end }}
data:
    {{- with .Values.gitWebhookProxy.config.provider }}
    provider: {{ . }}
    {{- end }}
    upstreamURL: {{ .Values.gitWebhookProxy.config.upstreamURL }}
    {{- with .Values.gitWebhookProxy.config.allowedPaths }}
    allowedPaths: {{ . }}
    {{- end }}
    ignoredUsers: {{ .Values.gitWebhookProxy.config.ignoredUsers | default "" | quote }}
    allowedUsers: {{ .Values.gitWebhookProxy.config.allowedUsers | default "" | quote }}
